### ISSUE TITLE
NPE in 1.20

### ISSUE THREAD

**Issue by nneul** [atlascommunity/jira-plugins-groovy#52]
Just upgraded my JIRA instance to 8.5.1 along with updating plugin from 1.19 to 1.20. Started seeing a NPE on every issue access in projects/workflows that were using the plugin. Also saw various 'can't display the issue at this time' when processing transitions. 

Start of the NPE:

`2019-12-07 16:11:23,203 http-nio-8080-exec-4 ERROR      [c.a.j.web.servlet.InternalServerErrorServlet] {errorId=5b29c3ba-6313-42c1-b97a-77c1fd4541ab, interpretedMsg=, cause=java.lang.NullPointerException, stacktrace=java.lang.NullPointerException
        at ru.mail.jira.plugins.groovy.impl.cf.FieldValueExtractor.doExtractValue(FieldValueExtractor.java:205) [?:?]
        at ru.mail.jira.plugins.groovy.impl.cf.FieldValueExtractor.lambda$getCachedValue$1(FieldValueExtractor.java:140) [?:?]
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2379) [?:?]
        at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853) [?:1.8.0_222]
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2377) [?:?]
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2360) [?:?]
        at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108) [?:?]
        at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62) [?:?]
        at ru.mail.jira.plugins.groovy.impl.cf.FieldValueExtractor.getCachedValue(FieldValueExtractor.java:134) [?:?]
        at ru.mail.jira.plugins.groovy.impl.cf.FieldValueExtractor.extractValueHolder(FieldValueExtractor.java:93) [?:?]
        at ru.mail.jira.plugins.groovy.impl.cf.FieldValueExtractor.extractValueHolder(FieldValueExtractor.java:81) [?:?]
        at ru.mail.jira.plugins.groovy.impl.cf.FieldValueExtractor.extractValue(FieldValueExtractor.java:65) [?:?]
        at ru.mail.jira.plugins.groovy.impl.cf.ScriptedCFType.getValueFromIssue(ScriptedCFType.java:50) [?:?]
        at com.atlassian.jira.issue.fields.ImmutableCustomField.getCustomFieldParamsFromIssue(ImmutableCustomField.java:1238) [classes/:?]
        at com.atlassian.jira.issue.fields.ImmutableCustomField.populateFromIssue(ImmutableCustomField.java:595) [classes/:?]
        at com.atlassian.jira.issue.fields.rest.FieldHtmlFactoryImpl$FieldRenderItemWithTab.populateFromIssue(FieldHtmlFactoryImpl.java:403) [classes/:?]
        at com.atlassian.jira.issue.fields.rest.FieldHtmlFactoryImpl.getPopulatedRenderableItems(FieldHtmlFactoryImpl.java:234) [classes/:?]
        at com.atlassian.jira.issue.fields.rest.FieldHtmlFactoryImpl.getEditFields(FieldHtmlFactoryImpl.java:160) [classes/:?]
        at sun.reflect.GeneratedMethodAccessor1190.invoke(Unknown Source) [?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [?:1.8.0_222]
        at java.lang.reflect.Method.invoke(Method.java:498) [?:1.8.0_222]
`

**Comment by nneul** [comment]
I can't test this on my production instance that was just upgraded (which I've rolled back to 1.19 to clear symptom) -- but should be able to try it again on my qa/dev instance if you would like me to try to get any more details or install a test build.

**Comment by lexek** [comment]
Hi, we published new version with a fix.

**Comment by nneul** [comment]
Thanks. Symptom is no longer present with that version of the plugin! Asking my users to confirm that all is working, but looks good.
