### ISSUE TITLE
JIRA 8.0 support?

### ISSUE THREAD

**Issue by nneul** [atlascommunity/jira-plugins-groovy#7]
Just to get something filed here - any idea when you might have the updates made to deal with all the changes atlassian made in 8.0? In particular, for MyGroovy looks like the primary impact is due to the Lucene change and corresponding change in object names/classes related to searches/results.

**Comment by lexek** [comment]
Hi, we're working on it.
Most likely it'll be publicly available next week.

**Comment by nneul** [comment]
Thank you! If you put an update here when you commit something on it, I'll be happy to try it from a source build.

**Comment by lexek** [comment]
You can try building from jira8 branch already.

**Comment by nneul** [comment]
And working beautifully for my current limited use case. Wonderful!

**Comment by nneul** [comment]
Small update - this actually is NOT working... It looks like it's functioning, however, it causes issues with the index. Rebuilds fail with this trace:

```
2019-03-04 14:32:27,137 IssueIndexer:thread-11 WARN nneul 872x101658x1 1y070p5 131.151.93.93,0:0:0:0:0:0:0:1 /secure/admin/jira/IndexReIndex.jspa [c.a.jira.index.AccumulatingResultBuilder] DocValuesField "mrg_links" appears more than once in this document (only one value is allowed per field)
java.lang.IllegalArgumentException: DocValuesField "mrg_links" appears more than once in this document (only one value is allowed per field)
	at org.apache.lucene.index.BinaryDocValuesWriter.addValue(BinaryDocValuesWriter.java:72)
	at org.apache.lucene.index.DefaultIndexingChain.indexDocValue(DefaultIndexingChain.java:543)
	at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:466)
	at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:392)
	at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:240)
	at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:497)
	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1729)
	at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1464)
	at com.atlassian.jira.index.WriterWrapper.addDocuments(WriterWrapper.java:75)
	at com.atlassian.jira.index.Operations$Create.perform(Operations.java:144)
	at com.atlassian.jira.index.Operations$Completion.perform(Operations.java:267)
	at com.atlassian.jira.index.DefaultIndexEngine$FlushPolicy.perform(DefaultIndexEngine.java:76)
	at com.atlassian.jira.index.DefaultIndexEngine.write(DefaultIndexEngine.java:138)
	at com.atlassian.jira.index.DefaultIndex.perform(DefaultIndex.java:28)
	at com.atlassian.jira.issue.index.DefaultIssueIndexer$IndexIssuesOperation.perform(DefaultIssueIndexer.java:460)
	at com.atlassian.jira.issue.index.DefaultIssueIndexer$IndexIssuesOperation.perform(DefaultIssueIndexer.java:444)
	at com.atlassian.jira.issue.index.DefaultIssueIndexer.lambda$null$2(DefaultIssueIndexer.java:371)
	at com.atlassian.jira.index.SimpleIndexingStrategy.apply(SimpleIndexingStrategy.java:7)
	at com.atlassian.jira.index.SimpleIndexingStrategy.apply(SimpleIndexingStrategy.java:5)
	at com.atlassian.jira.index.MultiThreadedIndexingStrategy$1.call(MultiThreadedIndexingStrategy.java:33)
	at com.atlassian.jira.index.MultiThreadedIndexingStrategy$1.call(MultiThreadedIndexingStrategy.java:31)
	at com.atlassian.jira.util.concurrent.BoundedExecutor$2.call(BoundedExecutor.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by nneul** [comment]
That error goes away if MyGroovy plugin is disabled.

**Comment by lexek** [comment]
Hi, @nneul 
I've pushed the fix to jira8 branch.
But other issue might come up after installing fixed version (something about different field type), and you might need to do locking re-index to fix that.

**Comment by nneul** [comment]
Looks like it's working smoothly, will let you know if I see anything else. Thank you!

**Comment by lexek** [comment]
We published today version for jira8.
